Updated Release 2.0.0
adessoAG/jekyll2cms pull request #78
Opened 2020-03-26 10:23 UTC by silasmahler

Introduces changes:

- add Gemfile.lock to gitignore -> file has to be removed in devblog repo
- use gitignore so delete methods are not needed
- refactor commit choosing logic: get diff between first commit that changes a post and its parents

2020-03-26 13:04 UTC, jo2 approved these changes

2020-03-27 10:49 UTC, s-gbz requested changes
So Leute! Erstmal wirklich zu betonen: Gute Arbeit! Das Programm hat wesentlich an Code verloren und scheint seine Aufgabe stabil ausführen zu können.

Um der nächsten Generation die sich damit beschäftigen wird den Einstieg noch leichter zu gestalten und Clean Code vor allem selbst zu verinnerlichen, habe ich nun einige Kommentare mit Vorschlägen hinterlassen. Ich weiß das es nach viel aussieht, allerdings muss man beachten, dass einfach nur viel Code mit dem selben Prinzip verfasst wurde. Die erläuterten und geforderten Prinzipien sind fast immer gleich. Stichwort SLA & SRP. (Mehr bzw. genug Erläuterung im Code)

Ich spare mir jetzt den Talk warum CC wichtig ist. Ich hoffe wir sind da bereits auf einem Nenner. Kommt gerne auf mich zu, falls ihr Erläuterungsbedarf seht 👍  :-)

PS: Da ihr den Code zusammen geschrieben habt, ist ein Review von Johannes in dem Fall nicht sehr sinnvoll, da ein solches Review immer von einer außenstehenden Person kommen muss. Gilt für absolut jeden Entwickler :)

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/ConfigService.java
> +                    "Please provide something in the format: https://github.com/myAccount/devblog.");
Don't Repeat Yourself (DRY) - Der Aufruf mit dem ersten Teil des Textes wiederholt sich im folgenden sehr oft. Hier könnte man eine `logEnvironmentVariableError(String missingVariableError)` oder ähnliches einführen, um dies einzusparen.

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/ConfigService.java
>          }
Single Responsibility Principle (SRP) - Jede der Checks auf Name, Mail & Passwort sollte eine eigene Methode sein.

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/ConfigService.java
>          if (GIT_AUTHOR_NAME == null) {
SRP

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/ConfigService.java
>          if (GIT_AUTHOR_MAIL == null) {
SRP

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/ConfigService.java
>          if (GIT_AUTHOR_PASSWORD == null) {
SRP

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/FileTransfer.java
>              if (source.lastModified() != dest.lastModified()) {
Clean Code beschreibt optimal wartbaren Code als ein Buch das sich von oben bis unten liest.
Das auslagern von bool checks in eigene Methoden fördert dies enorm weil aus einem solchen Statement die Bedeutung direkt ersichtlich wird. 

Als ich den Vergleich gerade direkt demonstrieren wollte, ist mir aufgefallen, dass ich auf Anhieb gar nicht verstehe worauf genau geprüft wird. Trotz Vermutung, dass es der Check eindeutig ist, bin ich mir nicht sicher was genau erwartet wird. Dies sollte vermieden werden.

`if(source.lastModified() != dest.lastModified())` vs. `if(sourceFileIsModified)` oder etwas völlig anderes?

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/FileTransfer.java
>      void copyFile(File source, File dest) {
Fast übersehen: Abkürzungen sollten im Gegenzug der Lesbarkeit vermieden werden. 

`source` = `sourceFile`,  `dest` = `fileDestination` = `fileToBeReplaced` = ?

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/FileTransfer.java
>              }
Single Level Of Abstraction (SLA) - Zugegeben ist es auf GitHub noch ein bisschen schwieriger zu lesen, weil neue & entferne Codesnippets vermischt sind. Dennoch:

SLA - Verwandt zu SRP. Eine Methode sollte eine Aufgabe erledigen. Die Abstraktion mehrerer Ebenen weist darauf hin, dass die Methode _mehr_ als das tut. Konkret: Geschachtelte Blöcke sind böse & erschweren die Les- & Testbarkeit. 1 Funktion - 1 Methode

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/ConfigService.java
> +    //GITHUB USERNAME
Clean Code sagt das sauber geschriebener Code keine Kommentare braucht. Wenn `GIT_AUTHOR_NAME` der `GITHUB USERNAME` ist, warum heißt das Feld nicht ensprechend so?

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/ConfigService.java
> +    //GITHUB USERNAME
Selbes gilt für Mail & Passwort.

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/ConfigService.java
> +                    "Please provide some Github-Username.");
```suggestion
                    "Please provide a Github-Username.");
```

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/ConfigService.java
> +                    "Please provide the provided GitHub user's Email.");
```suggestion
                    "Please provide the email of the specified GitHub user.");
```

An der Stelle: Warum brauchen wir hier die GitHub assoziierte email?

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/FileTransfer.java
>                  if (!dest.exists()) {
Siehe oben.

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/GitRepoCloner.java
> +            LOGGER.info("Repository cloned successfully.");
Theoretisch greift auch hier das SRP. Allerdings ist dies Geschmackssache & sollte sich an Teamstandards halten.
Ich erwähne es für Lernzwecke, halte es aber von meiner Seite für akzeptabel :)

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/GitRepoDiffer.java
>      public List<DiffEntry> checkForUpdates() {
Wenn ich richtig sehe, dass die Methode bis Zeile 104 (!) geht, ist sie _definitiv_ für mehr als eine Aufgabe zuständig und muss dringend aufgebröselt werden.

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/GitRepoDiffer.java
> +            Repository repo = LocalRepoCreater.getLocalGit().getRepository();
Von welchem `repo` ist hier die Rede? Ein `localRepo` ein `dummyRepo` ein anderer Fall den ich nicht sehe?

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/GitRepoDiffer.java
>                      .findFirst().orElse(null);
`search latest commit with changes done by a contributor who is not GIT_AUTHOR_NAME`
Klingt ganz so, also hättet ihr hier gerade den neuen Methodennamen des kommenden Blockes beschrieben :)

Dementsprechend: Den Block in eine eigene Methode auslagern.

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/GitRepoDiffer.java
>              }
Genau so hier 💯

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/GitRepoDiffer.java
>              }
Bitte für den Rest der Methode fortsetzen.

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/GitRepoDiffer.java
> +    private boolean checkOnPost(RevCommit commit) {
Was ist mit `checkOnPost` gemeint? -> Genauer *bennenen bitte.

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/GitRepoDiffer.java
> +    }
Bitte SRP & SLA anwenden.

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/GitRepoPusher.java
> +                if (status.isClean() || (status.getUntracked().size() == 1 && status.getUntracked().contains("Gemfile.lock"))) {
Was ist die Bedingung? Bitte refactoren wie oben mehrfach ausgeführt.

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/GitRepoPusher.java
>          Git localGit = LocalRepoCreater.getLocalGit();
`pushRepo` ist viel zu mächtig. Bitte refactoren wie oben mehrfach ausgeführt.

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/InitializationService.java
>  	public void init() {
`init`: Bitte refactoren wie oben mehrfach ausgeführt.

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/JekyllService.java
> +        //   call jekyll build
Kommenare sollten nur das warum erklären oder fachliche Zusammenhänge erklären. In diesem Fall: Sehr guter Einsatz eines Kommentars! 👍  :)

2020-03-27 10:49 UTC, s-gbz commented on src/main/java/de/adesso/service/MarkdownTransformer.java
> +				 * The Jekyll xml built is located at
```suggestion
				 * The generated xml is located at
```

2020-04-01 11:02 UTC, jo2 commented on src/main/java/de/adesso/service/InitializationService.java
>  	public void init() {
Was ist hier gemeint? Du bist vorher nie auf init oder dergleichen eingegangen?

2020-04-01 11:12 UTC, merged