change strategy to generate everything not in future and filter by git
adessoAG/jekyll2cms pull request #83
Opened 2020-03-30 15:29 UTC by jo2

* Remove Repo Differ
* Generate everything which is not in the future
* Use git do handle already generated and commited posts

2020-03-31 05:51 UTC, s-gbz requested changes

2020-03-31 05:51 UTC, s-gbz commented on src/main/java/de/adesso/service/GitRepoPusher.java
>                  if (status.isClean() || (status.getUntracked().size() == 1 && status.getUntracked().contains("Gemfile.lock"))) {
Was ist die Bedingung die erfüllt werden soll? -> In Methode auslagern

2020-03-31 05:51 UTC, s-gbz commented on src/main/java/de/adesso/service/GitRepoPusher.java
> +                status.getRemoved().forEach(file -> commitMessageBuilder.append("DELETE ").append(file).append("\n"));
Sieht wie eine eigene Methode aus -> `setGitStatusToXXX()` ?

2020-03-31 05:51 UTC, s-gbz commented on src/main/java/de/adesso/service/MarkdownTransformer.java
> +    protected void copyGeneratedXmlFiles() {
Für alle if Bedingungen die Methode auslagern und dann soll es für mich in Ordnung sein.

2020-03-31 05:51 UTC, s-gbz commented on src/main/java/de/adesso/service/MarkdownTransformer.java
> +    private void copyFile(Path sourcePath, String datePart) {
Ich glaube da hast du einen Punkt aus dem PR #78 bereits eingebaut? -> Very nice!

Eine Kleinigkeit noch: Was ist `datePart`? Ich dachte erst es sollte `destPath` sein, zweifle aber grad dran. Wenn es wirklich etwas mit dem Datum ist, würde z.B. `creationDate` jegliche Verwirrung vermeiden :)

2020-04-01 09:49 UTC, jo2 commented on src/main/java/de/adesso/service/MarkdownTransformer.java
> +    private void copyFile(Path sourcePath, String datePart) {
Das ist der Part des Dateinamens des Blogeintrags, der das Datum des Eintrags enthält. Ich mach mal nen Kommentar dran.

2020-04-01 10:42 UTC, silasmahler approved these changes

2020-04-01 10:42 UTC, merged